services:
  backend:
#    image: ghcr.io/a13xie/spring-example-backend:main
    image: a
    restart: unless-stopped
    secrets:
      - db-password
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=jspring
      - PW_FILE=/run/secrets/db-password
  db:
    image: postgres
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jspring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
